---
name: Chris Zubak-Skees

titles:
  - developer
  - designer
  - journalist

links:
  - title: Twitter
    icon: twitter
    url: https://twitter.com/zubakskees
  - title: GitHub
    icon: github
    url: https://github.com/chriszs
  - title: LinkedIn
    icon: linkedin-square
    url: https://www.linkedin.com/in/chriszs
  # - title: Email
  #   icon: paper-plane
  #   url: mailto:chris@zubak-skees.com

examples:
  - title: What first-quarter fundraising can tell us about 2020
    tag: data processing & analysis
    description: >-
      To show the state of presidential money, I crunched the data behind this
      graphics story designed and developed by Julia Wolfe of FiveThirtyEight. 
      The analysis used Python code and relied on a real-time SQL database of
      campaign finance information. It also informed the rest of filing day
      coverage.
    img: 2020fundraising.png
    url: https://projects.fivethirtyeight.com/2020-fundraising/

  - title: Suggested poems for Gmail
    tag: fun
    description: >-
      Released on April Fools' Day 2020, this browser extension replaced Gmail’s
      Smart Replies with lines of poetry. It was enjoyed by many, including
      Gmail project manager Paul Lambert, who wrote, “This is amazing. I wish we
      had thought of it!” It was mentioned on Lifehacker and The Verge. Nearly
      600 people installed it.
    img: poems.png
    url: https://chrome.google.com/webstore/detail/suggested-poems-for-gmail/kjjcalmhcemhafjcoanjjllfjdfnnhid

  - title: FEC loader
    tag: tool
    description: >-
      I released this set of flexible Node.js command line utilities designed to
      discover, convert and load raw Federal Election Commission filings into a
      database. This loads filings of unprecedented
      size with ease, allowing anyone to analyze FEC data in detail.
    img: fec.png
    url: https://github.com/PublicI/fec-loader/tree/subcommands

  - title: Abandoned in America
    tag: design & graphics
    description: >-
      This was an ambitious multi-part series on the places and people with
      little political clout. I designed and developed the presentation, as well as overseeing data analysis
      and graphics production.
    img: storm.png
    url: https://apps.publicintegrity.org/abandoned-in-america/disastrous-recovery

  - title: How ActBlue is trying to turn small donations into a blue wave
    tag: data processing & analysis
    description: >-
      I analyzed more than 80 million records in a nearly unprecedented analysis of Congressional
      Democratic candidates' reliance on this fundraising platform as it became the de facto way
      Democrats raise money.
    img: actblue.jpg
    url: https://fivethirtyeight.com/features/how-actblue-is-trying-to-turn-small-donations-into-a-blue-wave/

  - title: Public financial disclosure parser
    tag: tool
    description: >-
      I built a tool that helped four newsrooms build a database of Trump officials' financial histories. This was
      used to report daily stories by the New York Times and Washington Post, to build ProPublica's Trump Town
      news app and to report an award-winning national radio story with Reveal from the Center for Investigative Reporting.
      It caused at least one high-ranking official to revise his disclosures.
    img: citizensleuth.jpg
    url: https://github.com/PublicI/pfd-parser

  - title: Nuclear Negligence
    tag: story design
    description: >-
      Designed and developed the presentation for this series on the frightening near-misses in the nation's nuclear complex.
      Worked with an illustrator to develop a look and feel that helped tell the story.
    img: nuclear.png
    url: https://apps.publicintegrity.org/nuclear-negligence/

  - title: Share of women in elected office in every state
    tag: data graphic
    description: >-
      Charted data on the growth of women's representation in politics in the 50 states as the first state reached gender parity.
    img: women.png
    url: https://www.publicintegrity.org/2018/03/06/21606/share-women-elected-office-every-state

  - title: Death in the Trench
    tag: story design
    description: >-
      Designed this striking story on a preventable death and what it says about workplace safety enforcement.
    img: trench.png
    url: https://apps.publicintegrity.org/the-trench/

  - title: Find your state legislators' financial interests
    tag: app
    img: disclosures.png
    url: https://apps.publicintegrity.org/disclosure/statehouses/

  - title: Wilbur Ross will shepherd Trump’s trade policy. He also owns ships.
    tag: analysis & cartography
    img: ross.png
    url: https://www.publicintegrity.org/2017/03/23/14509/wilbur-ross-will-shepherd-trump-s-trade-policy-should-he-also-own-shipping-firm

  - title: Tracking TV ads in the 2016 state races
    tag: data processing & app
    img: stateads.png
    url: https://www.publicintegrity.org/2016/10/06/20290/tracking-tv-ads-2016-state-races

  - title: See how much the 2016 presidential candidates have raised so far
    tag: data processing & app
    img: electiontracker.png
    url: https://www.publicintegrity.org/2015/10/16/18631/see-how-much-2016-presidential-candidates-have-raised-so-far

  - title: Search the Nonprofit Network
    tag: data processing & app
    img: nonprofits.gif
    url: https://www.publicintegrity.org/2016/08/03/20030/search-nonprofit-network

  - title: Fatal Extraction
    tag: multimedia design
    img: fatalextraction.png
    url: https://projects.icij.org/fatalextraction/s/26

  - title: Title loans
    tag: data graphics
    img: titleloans.png
    url: https://www.publicintegrity.org/2015/12/09/18916/lawmakers-protect-title-loan-firms-while-borrowers-pay-sky-high-interest-rates

  - title: Ambassador fundraisers
    tag: data graphic
    img: ambassadors.png
    url: https://www.publicintegrity.org/ambassadors

  - title: Who's buying the Senate?
    tag: data graphic
    img: whosbuyingsenate.png
    url: https://www.publicintegrity.org/2014/09/02/15447/whos-buying-senate

  - title: China Leaks
    tag: graphic & devops
    img: china.png
    url: http://www.sueddeutsche.de/politik/interaktive-grafik-zu-offshore-leaks-geheime-geschaefte-der-maechtigen-und-reichen-1.1866146

  - title: Breathless and Burdened graphics
    tag: data graphics
    img: breathless.png
    url: https://www.informationisbeautifulawards.com/showcase/524-breathless-and-burdened-x-ray-readings-compared
